xelerance/Openswan

- programs/pluto/crypt_dh.c
- programs/pluto/ikev1_aggr.c
- programs/pluto/ikev1_main.c
- programs/pluto/ikev1_quick.c
- programs/pluto/pluto_crypt.h
This is an openswan specific fix for CVE 2015-3240, whereby an initiator sends an invalid g^x.
This code has been validated against the --impair- option created by the DHR for libreswan.
An automated unit test case may be possible in the future, but currently the unit test cases mock all the crypto.
> Cve 2015 3240

- programs/_confread/d.ipsec.conf/auto.xml
- programs/_confread/ipsec.conf.5
The manual option for auto keyword is no longer supported
> Updating man page in order to remove manual option from auto keyword

- programs/pluto/hostpair.h
additional issues in list_rm().
> protect list_rm against ehead being null

- programs/pluto/connections.c
- programs/pluto/hostpair.c
as a result of an instance being created/copied from the parent, without
clearing the IDhost_pair link
> the clear_IDhost_pair routine was complaining in list_rm()

- programs/pluto/ikev2.c
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_parent.c
- programs/pluto/timer.c
- tests/unit/libpluto/lp13-parentI3/output1.txt
- tests/unit/libpluto/lp46-rekeyikev2-I1/output1.txt
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
This is the result of the log file analysis of the beta of 2.6.48rc1: the conclusion was that the delete messages which eventually get sent out when an SA is rekeyed did not allocate their msgid properly, so they screwed up subsequent rekeys (which appear to be re-transmissions).
> T5149 delete reuses msgid

- programs/pluto/ikev1.c
- programs/pluto/ikev2_child.c
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/rekeyikev2-inCR1.c
IKEv2 code needs a transition_state to indicate which state (parent or child) should undergo the state transition, and this is provided for with the md->transition_state member.  
IKEv1 has simpler requirements (so far: there is actually the same mess buried), but if transition_state is not set, it should go with the previous behaviour.  This patch fixes the logic, which was inverted, which causes a core dump.
> IKEv1 fixes, from IKEv2 changes to MD

- programs/pluto/ikev2_child.c
- tests/unit/libpluto/lp57-rekeyv2nopfs-R1/output1.txt
This addresses the lack of nonce creation after the remote does a child rekey, and we respond with a Ni message reusing whatever nonce was in st_nr already. Now we will generate a new nonce, when we reply to a Ni message.
> T6606 regenerate nonce on rekey ack (attempt #2)

- include/constants.h
- include/ietf_constants.h
- include/names_constant.h
- lib/libopenswan/constants.c
- lib/libpluto/pluto_constants.c
- programs/pluto/ikev1.c
- programs/pluto/ikev1_main.c
- programs/pluto/ikev2.c
- programs/pluto/ikev2.h
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_notify.c
- programs/pluto/ikev2_parent.c
- programs/pluto/ikev2_parent_I1.c
- programs/pluto/ikev2_parent_R2.c
- tests/unit/libpluto/lp06-parentR1notchosen/output.txt
- tests/unit/libpluto/lp08-parentR1/output1.txt
- tests/unit/libpluto/lp13-parentI3/output1.txt
- tests/unit/libpluto/lp25-wrongcacert/output1.txt
- tests/unit/libpluto/lp45-h2hR1-noikev2/output1.txt
- tests/unit/libpluto/lp46-rekeyikev2-I1/output1.txt
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
- tests/unit/libpluto/lp50-rekey-no-reply-rekey/output1.txt
- tests/unit/libpluto/lp56-rekeyv2nopfs-I1/output1.txt
- tests/unit/libpluto/lp57-rekeyv2nopfs-R1/output1.txt
- tests/unit/libpluto/lp58-rekeyv2nopfs-inCR1/output1.txt
- tests/unit/libpluto/lp65-nattI3/output1.txt
- tests/unit/libpluto/run-unit-tests.sh
- tests/unit/libpluto/seam_demux.c
before we were able to interop with Strongswan, we would be generating a lot of N(INVAL) notification messages. The N(INVAL) messages were sent in response to messages from Strongswan that we did not understand. There were several issues with the way we generated N(INVAL) and that caused confusion on the Strongswan side, at which point SS killed the connection.
This work addresses the erroneous generation of notification messages to requests with encrypted payload.
A few minor changes were also made to error code lookup, and added new/missing IKEv2 parameters and corresponding strings.
> T6589 improve error messages (take 2)

- programs/pluto/ikev2.h
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_derived_keys.c
- programs/pluto/ikev2_parent_I3.c
- tests/unit/libpluto/lp12-parentR2/output1.txt
- tests/unit/libpluto/lp17-childselfpolicy/output2.txt
- tests/unit/libpluto/lp21-certreplyselfR2/output1.txt
- tests/unit/libpluto/lp22-certreplymanyR2/output1.txt
- tests/unit/libpluto/lp24-certreplydaveR2/output1.txt
- tests/unit/libpluto/lp39-h2hR2/output1.txt
- tests/unit/libpluto/lp47-rekeyikev2-R1/output1.txt
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
- tests/unit/libpluto/lp55-davecert-gatewayID-R2/output1.txt
- tests/unit/libpluto/lp57-rekeyv2nopfs-R1/output1.txt
- tests/unit/libpluto/lp58-rekeyv2nopfs-inCR1/output1.txt
- tests/unit/libpluto/lp64-nattR2/output1.txt
This pull request is for allowing pluto to use MD5 for keymaterial generation of a child SA negotiation, when MD5 is negotiated for the parent SA.  It was previously hardcoded to SHA1, and now uses the parent SA's negotiated alg value.
> T6453 md5 for keymat generation

- programs/pluto/ikev2.h
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_derived_keys.c
- programs/pluto/ikev2_parent_I3.c
- programs/pluto/state.c
- tests/unit/libpluto/lp12-parentR2/output1.txt
- tests/unit/libpluto/lp17-childselfpolicy/output2.txt
- tests/unit/libpluto/lp21-certreplyselfR2/output1.txt
- tests/unit/libpluto/lp22-certreplymanyR2/output1.txt
- tests/unit/libpluto/lp24-certreplydaveR2/output1.txt
- tests/unit/libpluto/lp39-h2hR2/output1.txt
- tests/unit/libpluto/lp47-rekeyikev2-R1/output1.txt
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
- tests/unit/libpluto/lp55-davecert-gatewayID-R2/output1.txt
- tests/unit/libpluto/lp57-rekeyv2nopfs-R1/output1.txt
- tests/unit/libpluto/lp58-rekeyv2nopfs-inCR1/output1.txt
- tests/unit/libpluto/lp64-nattR2/output1.txt
When reusing a state structure make sure that not just the endpoints match, but also the subnets.
> T6760 ikev2 subnet conn

- lib/libopenswan/secrets.c
if the PSK text was not quoted, the parser would log the secret text to syslog.
the solution is to only leak the secret if the plutodebug=private is enabled,
which is already leaking the PSK later in the process.
> wo#6532 - avoid leaking PSK text if it is malformed

- programs/pluto/ikev1_aggr.c
previously this was done with KH_ANY, which always failed to match connections
with both left= and right= defined.
> wo#6532 - use histype=KH_IPADDR to lookup connection

- programs/pluto/timer.c
previously, when EVENT_SA_REPLACE triggered, the code would incorrectly select
the latest child SA for comparison.  Since the child SA was always different
than the parent SA index, it would conclude that the rekey was not required,
and the parent SA would never rekey.
> wo#6532 - select the correct newest parent SA for EVENT_SA_REPLACE

- include/pluto/connections.h
- programs/pluto/ikev1.h
- programs/pluto/ikev2_parent.c
- programs/pluto/ikev2_parent_I1.c
- programs/pluto/ipsec_doi.c
- programs/pluto/ipsec_doi.h
- programs/pluto/pending.c
- programs/pluto/spdb_print.c
- programs/pluto/spdb_v2_struct.c
- programs/pluto/state.c
- programs/pluto/stubs.c
- tests/unit/libpluto/lp08-parentR1/output1.txt
- tests/unit/libpluto/lp10-parentI2/output1.txt
- tests/unit/libpluto/lp11-parentI2dup/output1.txt
- tests/unit/libpluto/lp13-parentI3/output1.txt
- tests/unit/libpluto/lp16-initiateselfI2/output1.txt
- tests/unit/libpluto/lp20-certificateselfI2/output1.txt
- tests/unit/libpluto/lp26-davecertI2/output1.txt
- tests/unit/libpluto/lp33-dnsload2/output.txt
- tests/unit/libpluto/lp38-h2hI2/output1.txt
- tests/unit/libpluto/lp43-parentM1/output.txt
- tests/unit/libpluto/lp46-rekeyikev2-I1/output1.txt
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
- tests/unit/libpluto/lp50-rekey-no-reply-rekey/output1.txt
- tests/unit/libpluto/lp54-davecert-gatewayID-I2/output1.txt
- tests/unit/libpluto/lp56-rekeyv2nopfs-I1/output1.txt
- tests/unit/libpluto/lp58-rekeyv2nopfs-inCR1/output1.txt
- tests/unit/libpluto/lp63-nattI2/output1.txt
- tests/unit/libpluto/lp65-nattI3/output1.txt
- tests/unit/libpluto/seam_pending.c
This pull requests fixes a bunch of little things that prevented a successful IKEv2 SA rekey (the parent SA), if the INITIATOR/RESPONDER roles became reversed.  That is if the original parent SA responder now initiated the parent SA rekey.  It would previously fail on the first such attempt, it's been observed to successfully reverse the INITIATOR/RESPONDER roles (with specially crafted code to induce this) 10+ times back-to-back without issues.
> T6874 parent sa rekey

- tests/unit/ikev2crypto/ct10-parentI2/output1.txt
- tests/unit/ikev2crypto/ct12-parentR2/output1.txt
- tests/unit/ikev2crypto/ct14-bigkeyI2/output1.txt
all these changes have already been incorporated into libpluto tests, but ikev2crypto tests have lagged behind.
> unit: update expected output of ikev2crypto unit tests

- programs/pluto/ikev2_parent.c
- programs/pluto/state.c
- programs/pluto/state.h
When receiving a IKE/parent SA delete request (or acknowledgement) pluto would be susceptible to a hash collision bug, where it would delete more SAs than was intended.  Part of the fix comes from Libreswan where this was already addressed.  Specifically the function delete_state_family() function added in commit f1cde81 is based on delete_my_family() which comes from Libreswan.
> T7003 deleting too many SAs

- tests/unit/libpluto/lp80-h2h-rekeyikev2-R2-msgid0/description.txt
- tests/unit/libpluto/lp81-h2h-rekeyikev2-I3-msgid0/description.txt
- tests/unit/libpluto/lp82-h2h-deleteSA-R2/description.txt
- tests/unit/libpluto/lp83-h2h-deleteSA-I3/description.txt
- tests/unit/libpluto/lp85-h2h-invalid-deleteSA-I3/description.txt
- tests/unit/libpluto/lp86-h2h-invalid-deleteSA-R2-R/description.txt
Michael noticed some inconsistencies between the documentation and actual test cases.
This commit addresses the documentations errors.
> wo#7456 . cleanup the documentation of unit tests lp{80..86}

- programs/pluto/ikev2_child.c
- tests/unit/libpluto/lp39-h2hR2/output1.txt
- tests/unit/libpluto/lp74-alg-h2hR2/output1.txt
- tests/unit/libpluto/lp75-alg-h2hI3/output1.txt
- tests/unit/libpluto/lp80-h2h-rekeyikev2-R2-msgid0/output1.txt
- tests/unit/libpluto/lp81-h2h-rekeyikev2-I3-msgid0/output1.txt
- tests/unit/libpluto/lp82-h2h-deleteSA-R2/output1.txt
- tests/unit/libpluto/lp83-h2h-deleteSA-I3/output1.txt
- tests/unit/libpluto/lp84-h2h-deleteSA-R2-R/output1.txt
- tests/unit/libpluto/lp85-h2h-invalid-deleteSA-I3/output1.txt
- tests/unit/libpluto/lp86-h2h-invalid-deleteSA-R2-R/output1.txt
- tests/unit/libpluto/lp90-h2h-sareplace-I1/output1.txt
- tests/unit/libpluto/lp91-h2h-sareplace-R1/output1.txt
fix IKEv2/rw/rsa conn eval when plutodebug=none
In DTP testing, a simple test case attempting IKEv2/rw/rsa would fail,
unless plutodebug=controlmore.
The bug was in ikev2_evaluate_connection_fit() where a large
DBG(DBG_CONTROLMORE,) block was updating ent point structures.
The fix is to move that code out of the DBG(DBG_CONTROLMORE,) block and
do it regardless.
This commit also fixed a typo in the messages logged (there was a missing close bracket)
and so the second commit fixes the unit tests affected.
> T7710 need controlmore debug for ikev2

- programs/pluto/ikev2.h
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_notify.c
- programs/pluto/ikev2_parent_I2.c
- programs/pluto/ikev2_parent_R2.c
- tests/unit/libpluto/lp63-nattI2/output1.txt
- tests/unit/libpluto/lp64-nattR2/output1.txt
- tests/unit/libpluto/lp65-nattI3/output1.txt
- tests/unit/libpluto/seam_natt.c
Before this set of changes, we would not enable IKEv2 NAT-T keepalives, unless there was an IKEv1 conn open that also required keepalives.
Existing unit tests were modified to require calling nat_traversal_new_ka_event() to enable the keepalives.
> T7615 ikev2 nat keepalives

- include/pluto_constants.h
- lib/libopenswan/subnettypeof.c
- lib/libpluto/pluto_constants.c
- linux/include/openswan.h
- programs/pluto/connections.c
- programs/pluto/ikev2_child.c
- programs/pluto/initiate.c
- tests/functional/01-confread/Makefile
- tests/functional/01-confread/n2n-transport.conf
- tests/functional/01-confread/n2n-transport.conf.out
- tests/unit/libpluto/lp03-whacksemantics/.gitignore
- tests/unit/libpluto/lp03-whacksemantics/Makefile
- tests/unit/libpluto/lp03-whacksemantics/output1.txt
- tests/unit/libpluto/lp03-whacksemantics/output2.txt
- tests/unit/libpluto/lp03-whacksemantics/output3.txt
- tests/unit/libpluto/lp03-whacksemantics/whacksemantics.c
Through testing 2.6.51, I discovered that pluto would negotiate a net2net conn in transport mode.
First, we will refuse to create a conn like this in ikev2_evaluate_connection_fit().  This prevents a peer from tricking us into accepting this config.
Second, we mark such configuration as INVALID and NEVER_NEGOTIATE.  This prevents us from negotiating this ourselves.
There is a DTP test case, and unit test cases associated with the bug.
> T7613 net2net transport

- programs/pluto/connections.c
Earlier changes for issue 7613, caused a regression in shunt policies being marked as INVALID.
This has been corrected.
There is a new DTP test case to validate this.
> wo#8115 - skip transport w/ subnet protection for shunt connections

- contrib/scripts/pluto-log-merge.pl
- programs/pluto/ikev2_child.c
- tests/unit/libpluto/lp48-rekeyikev2-inCR1/output1.txt
- tests/unit/libpluto/lp58-rekeyv2nopfs-inCR1/output1.txt
- tests/unit/libpluto/lp80-h2h-rekeyikev2-R2-msgid0/output1.txt
This fixes a RESPONDER trying to forcefully initiate a CHILD_SA rekey, by calling ipsec auto --up once the conn was established.
There were two problems: (1) when INITIATOR was replying to the request it would use the wrong keys to encrypt the message, and (2) when INITIATOR was replying it would mix up the subnets for TSi/TSr messages.
> T7302 nopfs responder rekey

- programs/pluto/ipsec_doi.c
- programs/pluto/replace.c
- tests/unit/libpluto/lp66-natt-replaceI/output1.txt
When replacing a parent SA, we were losing the policy settings.  It was impossible for IKEv1 to rekey the parent SA.  The fix was to pass the connection policy down to ipsecdoi_replace().  We now pass DTP ikev1/rw-psk-nat-rekey test case.
> wo#8102 - retain connection policy when calling ipsecdoi_replace() on parent SA

- include/pluto/connections.h
- programs/pluto/ikev2.c
- programs/pluto/ikev2.h
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_parent.c
- programs/pluto/ikev2_parent_I1.c
- programs/pluto/ikev2_parent_I2.c
- programs/pluto/initiate.c
- programs/pluto/spdb_print.c
- tests/unit/libpluto/lp08-parentR1/R1notify-dump.txt
- tests/unit/libpluto/lp08-parentR1/output1.txt
- tests/unit/libpluto/lp70-invalid-init-msg/output1.txt
- tests/unit/libpluto/lp85-h2h-invalid-deleteSA-I3/output1.txt
- tests/unit/libpluto/run-unit-tests.sh
Many changes to make us behave properly, when both sides have multiple proposals with differing DH groups.  Corrected notification generation (we would sometimes send double notifications for a failure).  We now inspect and reject a v2KE payload DH group, if it differs from what was negotiated.  If negotiation can be retired, then a failure will trigger a second attempt with a different DH group.  Unit tests updated where appropriate.
> T7347 dh group proposal

- lib/libpluto/pluto_constants.c
- tests/unit/libpluto/lp06-parentR1notchosen/output.txt
- tests/unit/libpluto/lp45-h2hR1-noikev2/output1.txt
previously calling stf_status_name(STF_FAIL+1) would print "STF_FAIL+9"
which is incorrect.  This change subtracts STF_FAIL before printing
the trailing number.  The new function will output "STF_FAIL+1" as
expected.
> correct how STF_FAIL+x is generated by stf_status_name()

- Makefile
passing MAKEFLAGS explicitly breaks builds on systems where /bin/sh symlinks to dash.
> wo#8180 - do not pass MAKEFLAGS explicitly

- include/pluto/dpd.h
- programs/pluto/dpd.c
- programs/pluto/pluto_crypt.h
- programs/pluto/state.h
- tests/functional/readwritetest
this PR is for porting a fix from Libreswan to OpenSWAN that allows us to interop with OpenBSD as described in the commit authored by Paul Wouters.
> T7411 dpd sequence

- lib/libipsecconf/keywords.c
- lib/libipsecconf/parser.l
- lib/libipsecconf/parser.y
- tests/functional/01-confread/cassidy.conf
- tests/functional/01-confread/cassidy.conf.out
- tests/functional/01-confread/cassidy/etc/ipsec.d/ssw.conf
As stated in d0da38c, this is a port of the fix applied to libreswan in commit 2a6f1b5e987d72486b1b7eaef5f28807a48802fb, by D. Hugh Redelmeier.
After this commit, dpddelay and dpdtimeout can take values with a suffix (s,m,h,d,w).
> T8451 dpd time args

- programs/pluto/ikev2.c
In IKEv2 I1/R1 we have already deleted the state when we saw STF_TOOMUCHCRYPTO returned by build_ke() or build_nonce().  It does not make sense to try cleaning it up.
> wo#8897 - avoid assert when handling STF_TOOMUCHCRYPTO on build_ke()

- programs/pluto/hostpair.c
- programs/pluto/ikev2.c
- programs/pluto/ikev2_child.c
- programs/pluto/ikev2_parent_R1.c
- programs/pluto/state.c
- tests/unit/libpluto/lp08-parentR1/output1.txt
Fix for crash when we interop with strongSwan when pfs=yes, IKE and phase2alg specify a different DH group, and strongSwan requests a rekey.
> T9094 pfs=yes rekey

- programs/pluto/kernel.c
programs/pluto/kernel.c:826:13: warning: duplicate ‘const’ declaration specifier [-Wduplicate-decl-specifier]
programs/pluto/kernel.c:24:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 12 and 16 bytes into a destination of size 15
> - 2 GCC warng:

- include/constants.h
- include/pluto/connections.h
- lib/libpluto/pluto_constants.c
- programs/pluto/connections.c
* incr static char buf
it was warn:
`
lib/libpluto/pluto_constants.c: In function ‘prettypolicy’:
lib/libpluto/pluto_constants.c:384:39: warning: ‘%s’ directive output may be truncated writing up to 8 bytes into a region of size between 0 and 200 [-Wformat-truncation=]
snprintf(buf, sizeof(buf), "%s%s%s%s%s%s%s"
^~
In file included from /usr/include/stdio.h:873,
from lib/libpluto/pluto_constants.c:23:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 1 or more bytes (assuming 240) into a destination of size 200
return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
__bos (__s), __fmt, __va_arg_pack ());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
+ include inttypes.h to have …
> Clean compile connections.c & decrementing warns in pluto_constants.c

- programs/pluto/adns.c
Incr 'status' size to get rid of
programs/pluto/adns.c: In function ‘master’:
programs/pluto/adns.c:332:50: warning: ‘%s’ directive output may be truncated writing up to 1026 bytes into a region of size 1017 [-Wformat-truncation=]
snprintf(status, sizeof(status), "query: %s", q.name_buf);
^~   ~~~~~~~~~~
In file included from /usr/include/stdio.h:873,
from programs/pluto/adns.c:45:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 8 and 1034 bytes into a destination of size 1024
return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
__bos (__s), __fmt, __va_arg_pack ());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> +16 to the buffer size of status

- lib/libpluto/writewhackmsg.c
Include <limits.h> for PATH_MAX to fix build failure under musl
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> lib/libpluto/writehackmsg.c: fix build on musl

- programs/pluto/ikev1_aggr.c
- programs/pluto/ikev1_main.c
- programs/pluto/ikev2_parent_I1.c
If the gateway initiates an ISAKMP SA rekey vs. a roadwarrior
peer it was sending packets to itself (0.0.0.0) and not using
the remote host/port info from the predecessor state.
> wo#10083 - Fix gateway rekey with roadwarrior peer

- programs/pluto/ikev1_quick.c
If the peer manages to send us a SA rekey, then accept it.
Strongswan will sometimes do this because OSW doesn't yet support
RFC4478 and is slower to rekey the Parent SA than strongswan would
like.
> wo#10213: Don't prevent responder peer from initiating SA rekey

- programs/pluto/ipsec_doi.c
Fixes a NULL pointer dereference when parent was NULL
> github#541: Fix segfault when rekeying child SA with no parent
